create table HSBA
(
    MAHSBA NUMBER(6) NOT NULL,
    MABN NUMBER(6) NOT NULL,
    NGAY DATE,
    CHANDOAN VARCHAR2(50),
    MABS NUMBER(6) NOT NULL,
    MAKHOA NUMBER(4) NOT NULL,
    MACSYT NUMBER(3) NOT NULL,
    KETLUAN VARCHAR2(100),
    CONSTRAINT HSBA_PK PRIMARY KEY
    (
        MAHSBA
    )
);

CREATE TABLE HSBA_DV
(
    MAHSBA NUMBER(6) NOT NULL,
    MADV NUMBER(5) NOT NULL,
    NGAY DATE NOT NULL,
    MAKTV NUMBER(6) NOT NULL,
    KETQUA VARCHAR2(50),
    CONSTRAINT HSBA_DV_PK PRIMARY KEY
    (
        MAHSBA,
        MADV,
        NGAY
    )
);

CREATE TABLE BENHNHAN
(
    MABN NUMBER(6) NOT NULL,
    MACSYT NUMBER(3) NOT NULL,
    TENBN VARCHAR2(30) NOT NULL,
    CMND NUMBER(12) NOT NULL,
    NGAYSINH DATE NOT NULL,
    SONHA NUMBER(3) NOT NULL,
    TENDUONG VARCHAR2(30) NOT NULL,
    QUANHUYEN VARCHAR2(30) NOT NULL,
    TINHTP VARCHAR2(30) NOT NULL,
    TIENSUBENH VARCHAR2(100),
    TIENSUBENHGD VARCHAR2(100),
    DIUNGTHUOC VARCHAR2(50),
    CONSTRAINT BENHNHAN_PK PRIMARY KEY
    (
        MABN
    )
);

CREATE TABLE CSYT
(
    MACSYT NUMBER(3) NOT NULL,
    TENCSYT VARCHAR2(200) NOT NULL,
    DCCSYT VARCHAR2(100) NOT NULL,
    SDTCSYT NUMBER(11) NOT NULL,
    CONSTRAINT CSYT_PK PRIMARY KEY
    (
        MACSYT
    )
);

CREATE TABLE NHANVIEN
(
    MANV NUMBER(6) NOT NULL,
    HOTEN VARCHAR2(30) NOT NULL,
    PHAI VARCHAR2(3) NOT NULL,
    NGAYSINH DATE NOT NULL,
    CMND NUMBER(12) NOT NULL,
    QUEQUAN VARCHAR2(50) NOT NULL,
    SODT NUMBER(9) NOT NULL,
    CSYT NUMBER(3) NOT NULL,
    VAITRO VARCHAR2(20) NOT NULL,
    CHUYENKHOA VARCHAR2(30),
    CONSTRAINT NHANVIEN_PK PRIMARY KEY
    (
        MANV
    )
);

ALTER TABLE HSBA
ADD CONSTRAINT FK1_HSBA FOREIGN KEY
(
    MACSYT
)
REFERENCES CSYT
(
    MACSYT
);

ALTER TABLE HSBA
ADD CONSTRAINT FK2_HSBA FOREIGN KEY
(
    MABN
)
REFERENCES BENHNHAN
(
    MABN
);

ALTER TABLE HSBA
ADD CONSTRAINT FK3_HSBA FOREIGN KEY
(
    MABS
)
REFERENCES NHANVIEN
(
    MANV
);

ALTER TABLE HSBA_DV
ADD CONSTRAINT FK1_HSBA_DV FOREIGN KEY
(
    MAHSBA
)
REFERENCES HSBA
(
    MAHSBA
);

ALTER TABLE HSBA_DV
ADD CONSTRAINT FK2_HSBA_DV FOREIGN KEY
(
    MAKTV
)
REFERENCES NHANVIEN
(
    MANV
);

ALTER TABLE BENHNHAN
ADD CONSTRAINT FK1_BENHNHAN FOREIGN KEY
(
    MACSYT
)
REFERENCES CSYT
(
    MACSYT
);
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK1_NHANVIEN FOREIGN KEY
(
    CSYT
)
REFERENCES CSYT
(
    MACSYT
);
--drop table CSYT CASCADE CONSTRAINTS; drop table HSBA CASCADE CONSTRAINTS; drop table HSBA_DV CASCADE CONSTRAINTS; drop table NHANVIEN CASCADE CONSTRAINTS; drop table BENHNHAN CASCADE CONSTRAINTS;  

commit;