alter session set "_ORACLE_SCRIPT"=true;  
alter session set container = xepdb1;
alter session set current_schema = hethong;

create table HSBA
(
    MAHSBA NUMBER(8) NOT NULL,
    MABN NUMBER(8) NOT NULL,
    NGAY DATE,
    CHANDOAN VARCHAR2(50),
    MABS NUMBER(8) NOT NULL,
    MAKHOA NUMBER(8) NOT NULL,
    MACSYT NUMBER(8) NOT NULL,
    KETLUAN VARCHAR2(100),
    CONSTRAINT HSBA_PK PRIMARY KEY
    (
        MAHSBA
    )
);

CREATE TABLE DICHVU
(
	MADV number(8) NOT NULL,
	TENDV varchar2(50),
	NGAYTHUCHIEN date,
	CONSTRAINT DICHVU_PK PRIMARY KEY(MADV)
);

CREATE TABLE HSBA_DV
(
    MAHSBA NUMBER(8) NOT NULL,
    MADV NUMBER(8) NOT NULL,
    NGAY DATE NOT NULL,
    MAKTV NUMBER(8) NOT NULL,
    KETQUA VARCHAR2(50),
    CONSTRAINT HSBA_DV_PK PRIMARY KEY
    (
        MAHSBA,
        MADV,
        NGAY
    )
);

CREATE TABLE BENHNHAN
(
    MABN NUMBER(8) NOT NULL,
    MACSYT NUMBER(8) NOT NULL,
    TENBN VARCHAR2(50) NOT NULL,
    CMND varchar2(12) NOT NULL,
    NGAYSINH DATE NOT NULL,
    SONHA varchar2(10) NOT NULL,
    TENDUONG VARCHAR2(30) NOT NULL,
    QUANHUYEN VARCHAR2(30) NOT NULL,
    TINHTP VARCHAR2(30) NOT NULL,
    TIENSUBENH VARCHAR2(100),
    TIENSUBENHGD VARCHAR2(100),
    DIUNGTHUOC VARCHAR2(50),
    CONSTRAINT BENHNHAN_PK PRIMARY KEY
    (
        MABN
    )
);

CREATE TABLE CSYT
(
    MACSYT NUMBER(8) NOT NULL,
    TENCSYT VARCHAR2(200) NOT NULL,
    DCCSYT VARCHAR2(100) NOT NULL,
    SDTCSYT varchar2(11) NOT NULL,
    CONSTRAINT CSYT_PK PRIMARY KEY
    (
        MACSYT
    )
);

CREATE TABLE NHANVIEN
(
    MANV NUMBER(8) NOT NULL,
    HOTEN VARCHAR2(30) NOT NULL,
    PHAI VARCHAR2(3) NOT NULL,
    NGAYSINH DATE NOT NULL,
    CMND varchar2(12) NOT NULL,
    QUEQUAN VARCHAR2(50) NOT NULL,
    SODT varchar2(10) NOT NULL,
    CSYT NUMBER(8) NOT NULL,
    VAITRO VARCHAR2(20) NOT NULL,
    CHUYENKHOA number(8),
    CONSTRAINT NHANVIEN_PK PRIMARY KEY
    (
        MANV
    )
);

CREATE TABLE KHOA
(
	MAKHOA number(8) NOT NULL,
	TENKHOA varchar2(50),
	SDTKHOA varchar2(15),
	CONSTRAINT KHOA_PK PRIMARY KEY(MAKHOA)
);

ALTER TABLE HSBA
ADD CONSTRAINT FK1_HSBA FOREIGN KEY
(
    MACSYT
)
REFERENCES CSYT
(
    MACSYT
);

ALTER TABLE HSBA
ADD CONSTRAINT FK2_HSBA FOREIGN KEY
(
    MABN
)
REFERENCES BENHNHAN
(
    MABN
);

ALTER TABLE HSBA
ADD CONSTRAINT FK3_HSBA FOREIGN KEY
(
    MABS
)
REFERENCES NHANVIEN
(
    MANV
);

ALTER TABLE HSBA
ADD CONSTRAINT FK4_HSBA FOREIGN KEY
(
    MAKHOA
)
REFERENCES KHOA
(
    MAKHOA
);

ALTER TABLE HSBA_DV
ADD CONSTRAINT FK1_HSBA_DV FOREIGN KEY
(
    MAHSBA
)
REFERENCES HSBA
(
    MAHSBA
);

ALTER TABLE HSBA_DV
ADD CONSTRAINT FK2_HSBA_DV FOREIGN KEY
(
    MAKTV
)
REFERENCES BENHNHAN
(
    MABN
);
ALTER TABLE HSBA_DV
ADD CONSTRAINT FK3_HSBA_DV_DICHVU FOREIGN KEY (MADV) REFERENCES DICHVU(MADV);
ALTER TABLE BENHNHAN
ADD CONSTRAINT FK1_BENHNHAN FOREIGN KEY
(
    MACSYT
)
REFERENCES CSYT
(
    MACSYT
);
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK1_NHANVIEN FOREIGN KEY
(
    CSYT
)
REFERENCES CSYT
(
    MACSYT
);
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK2_NHANVIEN FOREIGN KEY
(
    CHUYENKHOA
)
REFERENCES KHOA
(
    MAKHOA
);
--drop table CSYT CASCADE CONSTRAINTS; drop table HSBA CASCADE CONSTRAINTS; drop table HSBA_DV CASCADE CONSTRAINTS; drop table NHANVIEN CASCADE CONSTRAINTS; drop table BENHNHAN CASCADE CONSTRAINTS;drop table DICHVU CASCADE CONSTRAINTS;  drop table KHOA CASCADE CONSTRAINTS;

commit;